"""Criação da tabela Produto

Revision ID: 9d147df0a90b
Revises: 5add353ccb20
Create Date: 2025-04-20 16:09:04.170986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d147df0a90b'
down_revision = '5add353ccb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto')
    # ### end Alembic commands ###
